[theme]
primaryColor = "#2E334E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F6"
textColor = "#25282A"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
